apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeproject
  namespace: kubedemo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx_server
          image: nginx:1.12
          ports:
            - containerPort: 80
              protocol: TCP