apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: kubedemo
  labels:
    app: nginx
spec:
  ports:
    - port: 90
      targetPort: 80
      protocol: TCP
      name: nodeport1
  type: NodePort
  selector:
    app: nginx

